### ISSUE TITLE
Purpose of the warning and critical levels for Downstream and Upstream checks

### ISSUE THREAD

**Issue by uclara** [mcktr/check_tr64_fritz#38]
Hi,

I don't understand the purpose of the warning and critical levels for Downstream and Upstream checks. If for example I have a DSL line with max. 100Mbit/s DownstreamI get in 110Mbit/s connection rate in the DSL settings of the Fritz!Box.
I would like to check that the DSL connection is at least 100Mbit (warning level) and at least 80Mbit/s (critical level).

In the current version of check_tr64_fritz I get a critical status if I try to set this two levels in this way:

./check_tr64_fritz -h "192.168.187.1" -p "49443" -P "supersecret" -f "downstream" -w 100 -c 80
CRITICAL - Downstream 110 Mbit/s | downstream_rate=110 warn=100 crit=80

I think you should invers the logic for the Downstream and Upstream warning and critical levels to get a warning and critical alarm if the connection rate is lower than connection rate, as I get an OK status today if I set the warning and critical level higher as the expected connection rate:

./check_tr64_fritz -h "192.168.187.1" -p "49443" -P "supersecret" -f "downstream" -w 120 -c 150
OK - Downstream 110 Mbit/s | downstream_rate=110 warn=120 crit=150

Ulli

**Comment by mcktr** [comment]
Hi, 

thanks for reporting this issue.

I assume you are using the latest git master? With the introduction of the new check function `thermometer` I changed the behavior of how the warning and critical values are calculated. Before I release 2.2 I will take care of this.

Please don't use the git master branch in production, I know that the current documentation in installation chapter and just says that you should clone the repository. Use the latest stable release you can find [here](https://github.com/mcktr/check_tr64_fritz/releases). With the 2.1 release I could not reproduce it.

**Comment by mcktr** [comment]
I fixed it in the current master branch.

Please test it and if you experience any issues please report it :)

**Comment by uclara** [comment]
Hi mcktr,

that's fast :-)

I tested your fix and it seems working as expected ...

Ulli

**Comment by uclara** [comment]
Does the -w and -c parameters apply also for downstreamrate and upstreamrate?

At the moment I see only float numbers for up- and downstream rates ... and -c or -w with 0.10 doesn't have effect. I'm wondering it the -w/-c makes sense or not for that. Maybe to get alerts if the transfer rates exceeds certain levels ?

Ulli

**Comment by mcktr** [comment]
While fixing the issue I came across the same thought and I think that make sense. I created a separate issue for this #40. Please add your thoughts there. 

Thanks :+1:
