### ISSUE TITLE
Check FRITZ!Box LogFiles

### ISSUE THREAD

**Issue by uclara** [mcktr/check_tr64_fritz#41]
Hi,

which annoys me for a long time is the fact that's not possible to forward the Events/Logfiles from FRITZ!Box to a syslog/syslog-ng/rsyslog server ...

OK, with Freetz it is/was possible but it's not the way that i like ...

Do you know if it's possible to grab the FRITZ!Box events via tr64 protocol?

Ulli

**Comment by mcktr** [comment]
You can grab log entries through TR-064, but I don't know which events that are (e.g. all events, only internet connection events).

Maybe you can find more inside the AVM documentation: https://avm.de/service/schnittstellen/

Do you think a check function for log entries make sense? Currently I can't imagine how such a check should work.

**Comment by uclara** [comment]
I d'like to get the Events of different FRITZ!boxes and feed it to a syslog server or SPLUNK> for example ...
Could you give me some kind of start Help to realize a script that gets new events from a FRITZ!Box and send feeds it to a syslog server?

**Comment by mcktr** [comment]
I am currently writing a development documentation to explain how you can fetch TR-064 data from the Fritz!Box. This includes a simple script to fetch TR-064 raw data (basically XML). You could adopt the script and extend it with parsing the log entries and forward it to Splunk and/or a Syslog server.

The development documentation will be included inside the next release 2.2 but you can check out the master branch when #36 got merged to get the documentation earlier.

**Comment by mcktr** [comment]
Closing this in favor of #31
