### ISSUE TITLE
execvpe(/usr/lib/nagios/pluginsCustom/check_tr64_fritz) failed: Permission denied

### ISSUE THREAD

**Issue by syswombat** [mcktr/check_tr64_fritz#65]
hello
which permission have to be working
execvpe(/usr/lib/nagios/pluginsCustom/check_tr64_fritz) failed: Permission denied

i have done a 
chmod -R +x  check_tr64_fritz

and a restart of icinga2 but still the same information

**Comment by syswombat** [comment]
maybe it help
this is the Log:

[2018-07-21 23:23:32 +0200] warning/PluginCheckTask: Check command for object 'GW-01.kozo.ch!check_tr64_fritz' (PID: 13296, arguments: '/usr/lib/na
gios/pluginsCustom/check_tr64_fritz' '-P' 'icinga2pwd' '-f' 'status' '-h' '10.147.42.1' '-p' '49443' '-u' 'icinga2') terminated with exit code 128, ou
tput: execvpe(/usr/lib/nagios/pluginsCustom/check_tr64_fritz) failed: Permission denied

as i know it should be -h -p -u -P -f

**Comment by mcktr** [comment]
Please show me the permissions for the check script.

```
# ls -la /usr/lib/nagios/pluginsCustom/check_tr64_fritz 
```

**Comment by syswombat** [comment]
# ls -la /usr/lib/nagios/pluginsCustom/check_tr64_fritz
insgesamt 80
drwxr-xr-x 5 root root  4096 Jul 19 17:25 .
drwxr-xr-x 4 root root  4096 Jul 20 15:41 ..
-rwxr-xr-x 1 root root  2971 Jul 19 17:25 CHANGELOG.md
-rwxr-xr-x 1 root root 10695 Jul 19 17:25 check_tr64_fritz
drwxr-xr-x 2 root root  4096 Jul 19 17:25 devel
drwxr-xr-x 3 root root  4096 Jul 19 17:25 doc
-rwxr-xr-x 1 root root   890 Jul 19 17:25 getSecurityPort
drwxr-xr-x 8 root root  4096 Jul 19 17:25 .git
-rwxr-xr-x 1 root root    16 Jul 19 17:25 .gitignore
-rwxr-xr-x 1 root root 18046 Jul 19 17:25 LICENSE
-rwxr-xr-x 1 root root 12708 Jul 19 17:25 README.md

and installed/Config like http://wombat3.kozo.ch/j/icinga-list/9775-icinga2-add-fritzbox-7490

**Comment by mcktr** [comment]
The permissions are not the problem here.

The path for the check plugin is incomplete, you are referencing to the folder _check_tr64_fritz_. The complete path (in your configuration) is `/usr/lib/nagios/pluginsCustom/check_tr64_fritz/check_tr64_fritz`.

**Comment by syswombat** [comment]
Merci,
i did the change there
command = [ PluginCustomDir + "/check_tr64_fritz/check_tr64_fritz" ]

would the directory not be the same as the file i would - would have helped ;-)

Will i have to crate for everything to monitor a own file?
or it is possible to move the  vars.fritz_function = "status" information to the check_command?

**Comment by syswombat** [comment]
OK, now it is working! Thanks a lot for your support
![icinga-fritz](https://user-images.githubusercontent.com/3279451/43060903-72c6cd2a-8e42-11e8-8469-21e05c0a3129.PNG)

**Comment by mcktr** [comment]
I'll close this issue as resolved.
