### ISSUE TITLE
Some other examples for fetch_tr64_data.sh

### ISSUE THREAD

**Issue by uclara** [mcktr/check_tr64_fritz#72]
Hi,

thanks for your fetch_tr64_data.sh tool and the example ./fetch_tr64_data.sh -P [PASSWORD] -U deviceinfo -s DeviceInfo -a GetInfo ...

I see that not all FRITZ!Box logs will be read, but I'm far away to understand the AVM documentation to create or extend the searches. Could you please give a few more examples maybe with explanation where in the AVM documentation I can find the necessary parameters?

Thanks a lot!
Ulli

**Comment by mcktr** [comment]
The following will return the log: 

```
./fetch_tr64_data.sh -P <password> -U deviceinfo -s DeviceInfo -a GetDeviceLog
```

You can fetch the information for the `-U` parameter from [here](https://avm.de/fileadmin/user_upload/Global/Service/Schnittstellen/AVM_TR-064_overview.pdf). The other two parameters you can fetch from [here](https://avm.de/fileadmin/user_upload/Global/Service/Schnittstellen/deviceinfoSCPD.pdf). 

Alternative you can fetch a list directly from your Fritz!Box:

```
http://192.168.178.1:49000/tr64desc.xml
``` 

Also have a look into the First Steps [here](https://avm.de/fileadmin/user_upload/Global/Service/Schnittstellen/AVM_TR-064_first_steps.pdf). 

Does this help so far?

Best regards
Michael

**Comment by mcktr** [comment]
I am closing here for the lack of feedback.
